version: "3.8"

services:
  hello-next:
    build:
      context: .
      dockerfile: Dockerfile
    image: opklnm102/hello-next:local
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
